/*------------------------------------------------------------------------------------------------------*
                        USAGE
\*------------------------------------------------------------------------------------------------------*/
// 1. npm install
// 2. build:dev and build:prod npm scripts are compiling your code for development and production respectively.
// 3. npm start is starting a lite-server inside the build folder

const gulp = require("gulp");
const webpack = require("webpack");

const tasks = require("./tasks/gulptasks.js");
const { argv } = require("yargs");
const browserSync = require("browser-sync").create();

process.env.NODE_ENV = argv.production || "development";

const DEVELOPMENT = process.env.NODE_ENV === "development" ? true : false;

const webpackConfig =
    process.env.NODE_ENV === "production" ? "./webpack.config.prod.js" : "./webpack.config.js";

// run webpack to compile the script into a bundle
function compileJS(done) {
    return new Promise((resolve, reject) => {
        webpack(require(webpackConfig), (err, stats) => {
            if (err) {
                return reject(err);
            }

            if (stats.hasErrors()) {
                return reject(new Error(stats));
            }
            resolve();
        });
    });
}

function serve(done) {
    browserSync.init(
        {
            server: "./build",
            port: 3000,
            host: "0.0.0.0"
        },
        done
    );
}

function watch(done) {
    return gulp.watch(
        "**/*", // watch everything...
        {
            ignored: [
                // ...except for things generated by the build process.
                "build/**/*"
            ]
        },
        // when something changes, rebuild + reload
        gulp.series(tasks.clean, tasks.copyAssets, tasks.copyHtml, tasks.copyCss, compileJS, reload)
    );
}

function reload(done) {
    browserSync.reload();
    console.log(
        "ENV ===> " + (process.env.NODE_ENV === "development" ? "DEVELOPMENT" : "PRODUCTION")
    );

    done();
}

gulp.task("copy:html", tasks.copyHtml);
gulp.task("copy:css", tasks.copyCss);
gulp.task("copy:assets", tasks.copyAssets);
gulp.task(
    "server",
    gulp.series(
        tasks.clean,
        tasks.copyAssets,
        tasks.copyHtml,
        tasks.copyCss,
        compileJS,
        serve,
        watch
    )
);

// default includes all
gulp.task(
    "default",
    gulp.series(
        tasks.clean,
        tasks.copyAssets,
        tasks.copyHtml,
        tasks.copyCss,
        compileJS,
        serve,
        watch
    )
);
